export { default as Navbar } from "./navbar"
export { default as Accordion } from "./Accordion"
export { default as Typewriter } from "./TypeWriter"
export { default as Error } from "./error"
export { default as SearchComp } from "./Search"
export { default as Card } from "./Card"
