export { default as Programming } from "./programming"
export { default as DataStructures } from "./datastructures"
export { default as ControlStructures } from "./controlstructures"
export { default as FlowDiagrams } from "./flowdiagram"
export { default as Databases } from "./Databases"
export { default as Practices } from "./Practices"
export { default as Poo } from "./poo"